import type { Metadata } from "next";
import "./globals.css";
import { Roboto, Poppins } from "next/font/google";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  variable: "--roboto",
});
const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
  variable: "--poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-body">{children}</body>
    </html>
  );
}
